In [16]:
import numpy as np
from fold_unfold import Unfold_1, Unfold_2, Unfold_3

# Fold 1

In [6]:
def fold_1(Matrix, shape):

    Tensor = np.empty(shape)
    m, n, d = shape
    slice = 0

    for i in range(d):

        Tensor[:, :, i] = Matrix[:, slice : slice + Tensor[:, :, i].shape[0]].T
        slice = slice + Tensor[:, :, i].shape[0]
    
    return Tensor


# Fold 2

In [7]:
def fold_2(Matrix, shape):
    
    m, n, d = shape
    tensor = np.empty(shape)
    slice = 0 

    for i in range(m):

        tensor[i, :, :] = Matrix[:, slice : slice + tensor[i, :, :].shape[0]].T
        slice = slice + tensor[i, :, :].shape[0]
        
    return tensor

# Fold 3

In [8]:
def fold_3(Matrix, shape):
        
    m, n, d = shape
    Tensor = np.empty(shape)
    slice = 0 

    for i in range(n):
        
            Tensor[:, i, :] = Matrix[:, slice : slice + Tensor[:, i, :].shape[1]]
            slice = slice + Tensor[:, i, :].shape[1]

    return Tensor

# Test

In [14]:
TENSOR = np.array([
    [[4,  2], 
     [-3, 0], # Rear Face 1
     [0, -6],
     [-1, 1]],

    [[0, -2], 
     [1, -1], # Rear Face 2
     [3,  4],
     [5, -4]],

    [[10, 1],
     [5,  2], # Rear Face 3
     [-1, 4],
     [-2, 0]]
])


In [11]:
fold_1(Unfold_1(TENSOR), TENSOR.shape) == TENSOR

array([[[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]]])

In [12]:
fold_2(Unfold_2(TENSOR), TENSOR.shape) == TENSOR

array([[[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]]])

In [13]:
fold_3(Unfold_3(TENSOR), TENSOR.shape) == TENSOR

array([[[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]]])