In [85]:
import numpy as np

# unfold 1

In [86]:
def Unfold_1(Tensor):

        m, n, d = Tensor.shape
        unfolded_tensor = np.empty((n, m * d))
        slice = 0

        for i in range(d):
                
                unfolded_tensor[:, slice : slice + Tensor[:, :, i].shape[0]] = Tensor[:, :, i].T
                slice = slice + Tensor[:, :, i].shape[0]

        return unfolded_tensor

# unfold 2

In [87]:
def Unfold_2(Tensor):

    m, n, d = Tensor.shape
    unfolded_tensor = np.empty((d, m * n))
    slice = 0 

    for i in range(m):
        
            unfolded_tensor[:, slice : slice + Tensor[i, :, :].shape[0]] = Tensor[i, :, :].T
            slice = slice + Tensor[i, :, :].shape[0]

    return unfolded_tensor

# unfold 3

In [88]:
def Unfold_3(Tensor):
    
    m, n, d = Tensor.shape
    unfolded_tensor = np.empty((m, d * n))
    slice = 0 

    for i in range(n):
        
            unfolded_tensor[:, slice : slice + Tensor[:, i, :].shape[1]] = Tensor[:, i, :]
            slice = slice + Tensor[:, i, :].shape[1]

    return unfolded_tensor


In [93]:
Tensor= np.array([
    [[4,  2], 
     [-3, 0],
     [0, -6],
     [-1, 1]],

    [[0, -2], 
     [1, -1],
     [3,  4],
     [5, -4]],

     [[10, 1],
      [5,  2],
      [-1, 4],
      [-2, 0]]
])

# Test

In [94]:
Unfold_1(Tensor)

array([[ 4.,  0., 10.,  2., -2.,  1.],
       [-3.,  1.,  5.,  0., -1.,  2.],
       [ 0.,  3., -1., -6.,  4.,  4.],
       [-1.,  5., -2.,  1., -4.,  0.]])

In [95]:
Unfold_2(Tensor)

array([[ 4., -3.,  0., -1.,  0.,  1.,  3.,  5., 10.,  5., -1., -2.],
       [ 2.,  0., -6.,  1., -2., -1.,  4., -4.,  1.,  2.,  4.,  0.]])

In [96]:
Unfold_3(Tensor)

array([[ 4.,  2., -3.,  0.,  0., -6., -1.,  1.],
       [ 0., -2.,  1., -1.,  3.,  4.,  5., -4.],
       [10.,  1.,  5.,  2., -1.,  4., -2.,  0.]])